### PR TITLE
Make it extremely easy to boot up Starshot with DDEV

### PR DESCRIPTION
**Pull request by phenaproxima**
This supersedes #43.

I added a `.ddev` directory with a custom `install` command, making it ridiculously easy to set up Starshot with DDEV. This PR adds that to the README -- now folks who don't have PHP and Composer set up on the host machine, but _do_ have DDEV, will be able to get up and running almost as easily as if they did. It's essentially a one-liner.

### CODE REVIEW

**Comment by phenaproxima** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr50-gmt6jjbi67zsf3htivn54z1cvljcyraq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/663b7950009fd33a9d6f4791

**Comment by phenaproxima** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr50-gmt6jjbi67zsf3htivn54z1cvljcyraq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/663b7950009fd33a9d6f4791

**Comment by phenaproxima** [comment]
[Tugboat](https://www.tugboatqa.com) has finished building the preview for this pull request!

Link:
- https://pr50-gmt6jjbi67zsf3htivn54z1cvljcyraq.tugboatqa.com


Dashboard:
- https://dashboard.tugboatqa.com/663b7950009fd33a9d6f4791

**Comment by gitressa** [comment]
Beautiful @phenaproxima, your solution works perfectly, thanks!

**Comment by penyaskito** [comment]
:+1 thanks Adam for the promptness.

**Pull request merged**
